# access_token : the access token from the app you created in Mastodon at Settings - Development
# username : your username without the '@' or server domain.
# base_url : the base url of your Mastodon server, without the 'https://'
# days_to_keep : number of days to keep toots.
# keep_pinned : either True or False - if True, any pinned toots will be kept
# toots_to_keep : a List of toot ids indicating toots to be kept regardless of other settings
# hashtags_to_keep : a Set of hashtags, where any toots with any of these hashtags will be kept. Do not include the '#' symbol
# visibility_to_keep : any toots with visibility settings in this list will be kept. Options are: 'public', 'unlisted', 'private', 'direct'

# you can list only one user, or multiple users
# each user account should be preceded by a single dash, and indented, as per below
-
# ausglam.space account
  access_token : ZA-Yj3aBD8U8Cm7lKUp-lm9O9BmDgdhHzDeqsY8tlL0
  username : alice
  base_url : ausglam.space
  days_to_keep : 14
  keep_pinned : True
  toots_to_keep :
    - 103996285277439262
    - 103976473612749097
    - 103877521458738491
  hashtags_to_keep : !!set { python, glamblogclub }
  visibility_to_keep :
    - direct
    - private
-
# aus.social account
  access_token : AZ-Yj3aBD8U8Cm7lKUp-lm9O9BmDgdhHzDeqsY8tlL9
  username : bob
  base_url : aus.social
  days_to_keep : 30
  keep_pinned : False
  # toots_to_keep can be empty
  toots_to_keep :
    - 
  # hashtags_to_keep can be empty
  hashtags_to_keep : !!set { }
  # visibility_to_keep can be empty
  visibility_to_keep :
    - 
  